package com.example.taskprioritylist.domain.usecase

import com.example.taskprioritylist.domain.model.Task
import com.example.taskprioritylist.domain.repository.TaskRepository
import io.mockk.coJustRun
import io.mockk.coVerify
import io.mockk.mockk
import io.mockk.slot
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class AddTaskUseCaseTest {
    private val repository: TaskRepository = mockk()
    private lateinit var useCase: AddTaskUseCase

    @BeforeEach
    fun setUp() {
        useCase = AddTaskUseCase(repository)
    }

    @Test
    fun `GIVEN valid title WHEN invoke THEN repository addTask is called with trimmed title`() =
        runTest {
            val slot = slot<Task>()
            coJustRun { repository.addTask(capture(slot)) }

            useCase("  Buy milk  ", "", isImportant = false, isUrgent = false)

            assertEquals("Buy milk", slot.captured.title)
        }

    @Test
    fun `GIVEN blank description WHEN invoke THEN task description is null`() =
        runTest {
            val slot = slot<Task>()
            coJustRun { repository.addTask(capture(slot)) }

            useCase("Title", "   ", isImportant = false, isUrgent = false)

            assertNull(slot.captured.description)
        }

    @Test
    fun `GIVEN non-blank description WHEN invoke THEN task description is trimmed`() =
        runTest {
            val slot = slot<Task>()
            coJustRun { repository.addTask(capture(slot)) }

            useCase("Title", "  Some notes  ", isImportant = false, isUrgent = false)

            assertEquals("Some notes", slot.captured.description)
        }

    @Test
    fun `GIVEN isImportant true and isUrgent false WHEN invoke THEN task flags match`() =
        runTest {
            val slot = slot<Task>()
            coJustRun { repository.addTask(capture(slot)) }

            useCase("Title", "", isImportant = true, isUrgent = false)

            assertEquals(true, slot.captured.isImportant)
            assertEquals(false, slot.captured.isUrgent)
        }

    @Test
    fun `WHEN invoke THEN createdAt is non-zero`() =
        runTest {
            val slot = slot<Task>()
            coJustRun { repository.addTask(capture(slot)) }

            useCase("Title", "", isImportant = false, isUrgent = false)

            assertNotEquals(0L, slot.captured.createdAt)
        }

    @Test
    fun `WHEN invoke THEN task id is zero (auto-generated by Room)`() =
        runTest {
            val slot = slot<Task>()
            coJustRun { repository.addTask(capture(slot)) }

            useCase("Title", "", isImportant = false, isUrgent = false)

            assertEquals(0L, slot.captured.id)
        }

    @Test
    fun `WHEN invoke THEN repository addTask is called exactly once`() =
        runTest {
            coJustRun { repository.addTask(any()) }

            useCase("Title", "", isImportant = false, isUrgent = false)

            coVerify(exactly = 1) { repository.addTask(any()) }
        }
}
